// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Detects diseases in a plant from an image and returns a diagnosis with confidence levels.
 *
 * - detectDisease - A function that handles the plant disease detection process.
 * - DetectDiseaseInput - The input type for the detectDisease function.
 * - DetectDiseaseOutput - The return type for the detectDisease function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DetectDiseaseInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a plant, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type DetectDiseaseInput = z.infer<typeof DetectDiseaseInputSchema>;

const DetectDiseaseOutputSchema = z.object({
  diagnoses: z
    .array(
      z.object({
        disease: z.string().describe('The name of the potential disease.'),
        confidence: z
          .number()
          .describe('The confidence level of the diagnosis (0-1).'),
      })
    )
    .describe('A list of potential diseases and their confidence levels.'),
});
export type DetectDiseaseOutput = z.infer<typeof DetectDiseaseOutputSchema>;

export async function detectDisease(input: DetectDiseaseInput): Promise<DetectDiseaseOutput> {
  return detectDiseaseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'detectDiseasePrompt',
  input: {schema: DetectDiseaseInputSchema},
  output: {schema: DetectDiseaseOutputSchema},
  prompt: `You are an expert in plant pathology. Analyze the provided image of a plant and identify any potential diseases.

  Return a list of potential diseases and their confidence levels. The confidence level should be a number between 0 and 1.

  Image: {{media url=photoDataUri}}`,
});

const detectDiseaseFlow = ai.defineFlow(
  {
    name: 'detectDiseaseFlow',
    inputSchema: DetectDiseaseInputSchema,
    outputSchema: DetectDiseaseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
